### PR TITLE
PS-12-Created-packet-filtering-GUI

### PR DESCRIPTION
**Pull request by d3shira**
Implemented a `FilterPacketsGUI` class using Tkinter to provide a graphical interface for filtering packet data based on various criteria.

### CODE REVIEW

**Review by BlerttaKrasniqi — APPROVED** [review]
Nice job!

**Review by diartmaraj — APPROVED** [review]
Good job!

**Comment by d3shira** [comment]
> Nice job!

Thanks!

**Comment by d3shira** [comment]
> Good job!

Thanks!

**Pull request merged**
